config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  get 'home', to: 'home#home'
  get 'help', to: 'home#help'
  get 'contact', to: 'home#contact'
  post 'send_contact', to: 'home#send_contact'
  get 'about', to: 'home#about'
  get 'calendar', to: 'home#calendar'

  resources :communities do
    patch 'organizations', to: 'communities#add_member'
    delete 'organizations', to: 'communities#remove_member', as: 'remove_organization'
    get :podcast, to: 'communities#podcast'
    resources :subscribers, only: [:create, :destroy]
  end

  resources :organizations do
    patch 'users', to: 'organizations#add_user'
    delete 'users', to: 'organizations#remove_user'
    resources :roles, only: [:update]
    get :podcast, to: 'organizations#podcast'
    resources :subscribers, only: [:create, :destroy]
  end

  resources :posts do
    resources :locations
    resources :comments, only: [:create]
    resources :subscribers, only: [:create, :destroy]
    delete 'community', to: 'posts#remove_community'
    get :autocomplete_community_name, on: :collection
    get :get_og_data, on: :collection
  end

  get :events, to: 'posts#events', as: 'events'

  resources :comments, only: [:update, :destroy, :show] do
    resources :comments, only: [:create, :update, :destroy]
  end

  resources :searches, only: [:index]

  #resources :facebook_subscriptions, only: [:index, :create]
  get '/facebook_subscriptions', to: 'facebook_subscriptions#index', as: 'facebook_subscriptions'
  post '/facebook_subscriptions/', to: 'facebook_subscriptions#create'
  resources :badges

  resources :photos, only: [:index, :new, :create, :destroy]
  resources :audios, only: [:index, :destroy]

  get '/login' => 'user_sessions#new', as: :login
  get '/logout' => 'user_sessions#destroy', as: :logout
  resources :user_sessions, only: [:create, :new]
  resources :users
  resources :password_resets, only: [:new, :create, :edit, :update]
  get :send_merge, to: 'users#send_merge_email'
  get :merge_user, to: 'users#merge_user'
  put '/add_admin/:user_id', to: 'users#add_admin', as: 'add_admin'
  delete '/remove_admin/:user_id', to: 'users#remove_admin', as: 'remove_admin'


  get 'locations', to: 'locations#show'

  namespace :api do
    resources :posts do
      resources :locations, only: [:create, :update, :destroy]
      resources :communities, only: [:create, :update, :destroy]
      resources :subscribers, only: [:create, :destroy]
      resources :comments, only: [:create]
    end
    get 'today', to: 'posts#today'
    get 'tomorrow', to: 'posts#tomorrow'
    get 'next_week', to: 'posts#next_week'
    get :events, to: 'posts#events', as: 'events'

    resources :comments, only: [:update, :destroy, :show] do
      resources :comments, only: [:create, :update, :destroy]
    end

    resources :communities do
      resources :posts, only: [:create, :update, :destroy]
      resources :locations, only: [:create, :update]
      patch 'organizations', to: 'communities#add_member'
      delete 'organizations', to: 'communities#remove_member', as: 'remove_organization'
      resources :subscribers, only: [:create, :destroy]
    end

    resources :organizations do
      resources :posts, only: [:create, :update, :destroy]
      resources :locations, only: [:create, :update]
      patch 'users', to: 'organizations#add_user'
      delete 'users', to: 'organizations#remove_user'
      resources :subscribers, only: [:create, :destroy]
    end

    resources :locations, only: [:show, :create, :update, :destroy] do
      resources :posts, only: [:create, :update, :destroy]
    end

    resources :users do
      resources :posts, only: [:create, :update, :destroy]
    end

    resources :searches, only: [:index]
    resources :badges, only: [:index, :show]
  end

  get 'auth/facebook', as: 'auth_provider'
  get 'auth/facebook/callback', to: 'user_sessions#facebook_login'
  get 'auth/twitter', as: 'twitter_auth_provider'
  get 'auth/twitter/callback', to: 'user_sessions#twitter_login'
  get 'auth/google_oauth2', as: 'google_auth_provider'
  get 'auth/google_oauth2/callback', to: 'user_sessions#google_login'
  get 'auth/failure', to: 'user_sessions#auth_failure'


  root 'home#home'

  require 'sidekiq/web'
  require 'admin_constraint'
  mount Sidekiq::Web => '/kiq', :constraints => AdminConstraint.new
  # constraints lambda {|request| AuthConstraint.admin?(request) } do
  #   mount Sidekiq::Web => '/admin/kiq'
  # end

end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_paranoid
  has_secure_password
  dragonfly_accessor :photo

  attr_accessor :photo_web_url

  validates :username, allow_nil: true, allow_blank: true, uniqueness: true
  validates :email, allow_nil: true, uniqueness: true,
   format: { with: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9\.-]+\.[A-Za-z]+\Z/ }
  validates :web_link, allow_nil: true, allow_blank: true, format: { with: /(https?|ftp|file|ssh):\/\// }

  # TODO: Figure out how to validate, or skip validation, for gravatar URL images.
  #validates_property :ext, of: :photo, in: ['jpeg', 'jpg', 'png', 'gif', 'svg', 'svgz', 'JPG'], if: :photo_changed?
  validates_property :mime_type, of: :photo,
                     in: ['image/jpeg', 'image/png', 'image/gif', 'image/svg+xml', 'image/svg', 'application/octet-stream'],
                     if: :photo_changed?
  validates_property :format, of: :photo, in: ['jpeg', 'png', 'gif', 'svg', 'svgz'], if: :photo_changed?

  has_many :posts
  has_many :comments
  has_many :subscriptions, :class_name => "Subscriber", :foreign_key => "user_id"
  has_many :facebook_subscriptions
  has_many :roles
  has_and_belongs_to_many :communities
  has_and_belongs_to_many :organizations
  has_and_belongs_to_many :badges

  before_save :downcase_email
  before_validation :set_photo

  def self.facebook(auth)
    @facebook = Koala::Facebook::API.new(auth['token'])
  end

  def self.twitter(auth_hash)

    user = User.find_by(twitter_id: auth_hash.uid)
    if user.nil?
      user = User.find_by(username: auth_hash.info.nickname)
    end
    if user.nil?
      user = create(username: auth_hash.info.nickname, password: (0...50).map { ('a'..'z').to_a[rand(26)] }.join)
    end

    name = auth_hash.info.name.split(' ') unless auth_hash.info.name.nil?
    if user.photo.nil?
      user.photo_url = auth_hash.info.image unless auth_hash.info.image.nil?
    end
    user.first_name = name[0] unless name[0].nil?
    user.last_name = name[-1] unless name[-1].nil?

    user.twitter_id = auth_hash.uid
    user.twitter_token = auth_hash.credentials.token
    user.twitter_secret = auth_hash.credentials.secret
    user.twitter_link = auth_hash.info.urls.Twitter

    user.save
    user
  end

  def self.google(auth_hash)
    user = User.find_by(email: auth_hash.info.email)
    if user.nil?
      user = create(email: auth_hash.info.email, password: (0...50).map { ('a'..'z').to_a[rand(26)] }.join)
    end

    if user.photo.nil?
      user.photo_url = auth_hash.info.image unless auth_hash.info.image.nil?
    end
    user.first_name = auth_hash.info.first_name unless auth_hash.info.first_name.nil?
    user.last_name = auth_hash.info.last_name unless auth_hash.info.last_name.nil?
    user.email = auth_hash.info.email

    user.google_id = auth_hash.uid
    user.google_token = auth_hash.credentials.token
    user.google_link = auth_hash.extra.raw_info.profile

    user.save
    user
  end

  def downcase_email
    self.email = email.strip.downcase unless email.nil?
  end

  def set_photo
    unless self.email.nil?
      if self.photo.nil?
        hash = Digest::MD5.hexdigest(downcase_email)
        self.photo_url = "http://gravatar.com/avatar/#{hash}?s=150"

        # Not sure why I have to save here, but it doesn't keep the photo info if I don't.
        self.save
      end
    end
  end

  def set_username
    username = email.split('@')[0] unless email.nil?
    if User.find_by(username: username)
      self.username = username + '_' + (0...5).map { ('a'..'z').to_a[rand(26)] }.join unless email.nil?
    else
      self.username = username unless email.nil?
    end
  end

  def generate_password_reset_token!
    update_attribute(:password_reset_token, SecureRandom.urlsafe_base64)
  end

  def generate_user_merge_token!
    update_attribute(:merge_token, SecureRandom.urlsafe_base64)
  end

  def admin?
    true if Role.where(user_id: self.id, name: 'admin')[0]
  end

  def explicit?
    true if explicit
  end

  def as_json(options={})
    self.photo_web_url = self.photo.url if self.photo
    super(methods: :photo_web_url, :only => [
        :id,
        :first_name,
        :last_name,
        :email,
        :created_at,
        :username,
        :facebook_id,
        :facebook_link,
        :twitter_id,
        :twitter_link,
        :google_id,
        :google_link,
        :web_link,
        :photo_name,
        :photo_web_url,
        :role
    ], :include => {
              :communities => { only: [:id, :name, :description]},
              :organizations => { only: [:id, :name, :description]}
                                 })
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < Api::ApiController
  before_filter :authenticate, only: [:index, :show, :update, :destroy]

  def index
    if current_user.nil?
      render status: 401, json: {
                            errors: 'Unauthorized.'
                        }.to_json
    else
      if current_user.role == 'admin'
        users = User.all
        render status: 200, json: users.as_json
      else
        render status: 422, json: {
                              errors: 'Method not allowed.'
                          }.to_json
      end
    end
  end

  def show
    render json: current_user.as_json()
  end

  def create
    user = User.new(user_params)
    if user.save
      # Send welcome email.
      Notifier.send_welcome(user).deliver_now

      render status: 200, json: {
                            message: 'User created.',
                            user: user
                        }.to_json
    else
      render status: 422, json: {
                            errors: user.errors
                        }.to_json
    end
  end

  def update
    if current_user.update(user_params)
      ApplyBadgesJob.perform_now(current_user)
      render status: 200, json: {
                            message: 'User updated.',
                            user: current_user
                        }.to_json
    else
      render status: 422, json: {
                            message: 'User could not be updated.',
                            user: current_user
                        }.to_json
    end
  end

  def destroy
    current_user.destroy

    render status: 200, json: {
                          message: 'User deleted.'
                      }.to_json
  end

  private
  def user_params
    params.require('user').permit(:email, :password, :first_name, :last_name, :username, :web_link,
                                  :photo, :role, :notify_instant, :notify_daily, :notify_weekly, :community_ids => [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:index, :show, :edit, :update, :destroy, :merge_user]

  def index
    unless current_user.admin?
      redirect_to home_path
    end
    @users = User.all
  end

  def show
    @posts = @user.posts.order('created_at DESC').paginate(:page => params[:page], :per_page => 5)
  end

  # GET /users/new
  def new
    if current_user
      flash[:success] = 'Welcome you have successfully registered.'
      redirect_to home_path
    end
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    if not current_user == @user
      flash[:error] = 'You can only update your profile.'
      redirect_to '/users/' + @user.id.to_s
    end
  end

  # Get /user_merge
  def send_merge_email
    merge_user = User.find_by(email: params[:email])

    if merge_user.facebook_id.nil? or merge_user.twitter_id.nil?
      merge_user.generate_user_merge_token!
      Notifier.send_merge(merge_user).deliver_now
      flash[:success] = 'Merge request sent! Please check your email.'
      redirect_to current_user
    else
      flash[:alert] = 'Cannot request merge for this email.'
      redirect_to current_user
    end
  end

  def merge_user
    @user = User.find_by(merge_token: params[:format])

    @user.first_name = current_user.first_name if @user.first_name.nil?
    @user.last_name = current_user.last_name if @user.last_name.nil?
    @user.facebook_id = current_user.facebook_id if @user.facebook_id.nil?
    @user.twitter_id = current_user.twitter_id if @user.twitter_id.nil?
    @user.google_id = current_user.google_id if @user.google_id.nil?
    @user.facebook_link = current_user.facebook_link if @user.facebook_link.nil?
    @user.twitter_link = current_user.twitter_link if @user.twitter_link.nil?
    @user.google_link = current_user.google_link if @user.google_link.nil?
    @user.merge_token = nil

    if @user.save
      # Update all posts.
      current_user.posts.each do |post|
        post.user = @user
        post.save
      end

      # Update all communities created_by.
      Community.where(created_by: current_user.id).each do |community|
        community.created_by = @user.id
        community.save
      end

      # Set the username here since it has to be unique.
      username = current_user.username

      # Remove FacebookSubscriptions.
      FacebookSubscription.where(user_id: current_user.id).each do |sub|
        sub.destroy
      end

      current_user.really_destroy!
      @user.username = username if @user.username.nil?
      @user.save

      session[:user_id] = nil
      reset_session
      flash[:notice] = 'Hurray! Your account setup with email and the new account setup via social network have been merged, you can now login with email or social network accounts.'
      redirect_to login_path
    else
      flash[:alert] = "There was a problem merging your account: #{@user.errors.full_messages[0]}"
      redirect_to current_user
    end
  end

  def create
    @user = User.new(user_params)

    if @user.save
      # Send welcome email.
      Notifier.delay.send_welcome(@user)

      session[:user_id] = @user.id
      flash[:success] = 'Welcome you have successfully registered.'
      redirect_to root_path
    else
      if @user.errors.has_key?(:email)
        flash[:alert] = "Email #{@user.errors.get(:email)[0]}."
        redirect_to new_user_path
      else
        @user = User.only_deleted.find_by(email: user_params[:email])
        if @user
          User.restore(@user)
          @user.password = user_params[:password]
          @user.save

          Notifier.send_welcome(@user).deliver_now
          session[:user_id] = @user.id
          redirect_to home_path, success: 'Welcome you have successfully registered.'
        else
          render :new
        end
      end
    end
  end

  def update
    if current_user == @user
      if @user.update(user_params)
        ApplyBadgesJob.perform_now(current_user)
        flash[:success] = 'Profile successfully updated.'
        redirect_to @user
      else
        puts "user.errors: #{@user.errors.full_messages}"
        if @user.errors[:email].include?('has already been taken')
          flash[:alert] = "Sorry, that email has already been taken. Click ".html_safe +
          " <a href='/send_merge?email=#{@user.email}'><strong>here</strong></a> to merge accounts.".html_safe
        end
        render :edit
      end
    elsif current_user.admin?
      if @user.update(user_params)
        flash[:success] = 'User successfully updated.'
        redirect_to @user
      else
        flash[:alert] = 'Problem updating user.'
        redirect_to :edit
      end
    else
      flash[:alert] = 'You can only update your profile.'
      redirect_to @user
    end
  end

  def destroy
    if current_user == @user
      @user.destroy
      session[:user_id] = nil
      reset_session
      redirect_to home_path, notice: 'User was successfully destroyed.'
    elsif current_user.admin?
      @user.destroy
      session[:user_id] = nil
      reset_session
      redirect_to home_path, notice: 'User was successfully destroyed.'
    else
      flash[:error] = 'You can only delete your account.'
      redirect_to '/users/' + @user.id.to_s
    end
  end

  def add_admin
    if Role.create(user: User.find(params[:user_id]), name: 'admin')
      flash[:success] = 'Admin role added.'
    else
      flash[:error] = 'There was a problem adding the Admin role.'
    end
    redirect_to users_path
  end

  def remove_admin
    user = User.find(params[:user_id])
    role = Role.where(user_id: user.id, name: 'admin')[0]
    if role.destroy
      flash[:success] = 'Admin role removed.'
    else
      flash[:error] = 'There was a problem removing Admin role.'
    end
    redirect_to users_path
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email,
                                 :password, :username, :web_link,
                                 :photo, :role, :bio, :explicit,
                                 :retained_photo, :facebook_link,
                                 :twitter_link, :google_link,
                                 :notify_instant, :notify_daily,
                                 :notify_weekly)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_change_password_form.html.erb
<%= form_for(@user, :builder => FoundationFormBuilder) do |f| %>



  <%= f.password_field :password, placeholder: 'New Password' %>


    <div class="row">
      <div class="large-4 columns actions">
        <%= button_tag type: 'submit', class: 'button small success' do %>
            <%= image_tag 'save-icon.svg', class: 'ty-icon' %>
            &nbsp;
            Update Password
        <% end %>
      </div>
    </div>


<% end %>

app/views/users/_edit_form.html.erb
<%= form_for(@user, data: {'abide' => true}) do |f| %>

    <div class="row">
      <div class="large-4 columns">
        <fieldset>
          <legend>Details</legend>

          <div class="row">
            <div class="large-12 columns">
              <% if @user.photo  %>
                  <%= image_tag @user.photo.thumb('150x150#').url, :class => 'avatar' %>
              <% else %>
                  <%= image_tag 'avatar.svg', :class => 'avatar' %>
              <% end %>

              <%= image_tag 'swap-icon.svg', size: '75x75', class: 'hidden swap' %>
              <%= image_tag 'avatar.png', class: 'hidden image_to_upload' %>

              <%= f.file_field :photo, class: 'photo_upload' %>
              <%= f.hidden_field :retained_photo %>
            </div>
          </div>
          <br/>

          <div class="row">
            <div class="large-12 columns">
              <%= f.label :first_name %>
              <%= f.text_field :first_name, actionname: action_name %>
            </div>
          </div>

          <div class="row">
            <div class="large-12 columns">
              <%= f.label :last_name %>
              <%= f.text_field :last_name, actionname: action_name %>
            </div>
          </div>

          <div class="row">
            <div class="large-12 columns">
              <%= f.label :email %>
              <%= f.text_field :email, actionname: action_name %>
            </div>
          </div>

          <div class="row">
            <div class="large-4 columns actions">
              <% if  @user.errors[:email].include?('has already been taken') %>
                  <% if !current_user.facebook_id.nil? || !current_user.twitter_id.nil? %>
                      <%= link_to 'Click Here To Request Merge', send_merge_path,
                                  :id => 'merge_link',
                                  :class => 'button tiny' %>
                  <% end %>
              <% end %>
            </div>
          </div>

          <div class="row">
            <div class="large-12 columns">
              <%= f.label :username %>
              <%= f.text_field :username %>
            </div>
          </div>
        </fieldset>
      </div>
    </div>

    <div class="row">
      <div class="large-4 columns">
        <fieldset id="userWebLinks">
          <legend>Links</legend>
          <div class="row">
            <div class="large-12 columns">
              <%= f.label :web_link %>
              <%= f.text_field :web_link, pattern: 'url', placeholder: 'http://$your_domain.com' %>
              <small class="error">Must be full URL, for example: http://google.com</small>
            </div>
          </div>

          <div class="row">
            <div class="large-12 columns">
              <%= f.label :facebook_link %>
              <%= f.text_field :facebook_link, pattern: 'url', placeholder: 'https://www.facebook.com/$your_username' %>
              <small class="error">Must be full URL, for example: http://google.com</small>
            </div>
          </div>

          <div class="row">
            <div class="large-12 columns">
              <%= f.label :twitter_link %>
              <%= f.text_field :twitter_link, pattern: 'url', placeholder: 'https://twitter.com/$your_username' %>
              <small class="error">Must be full URL, for example: http://google.com</small>
            </div>
          </div>

          <div class="row">
            <div class="large-12 columns">
              <%= f.label :google_link %>
              <%= f.text_field :google_link, pattern: 'url', placeholder: 'https://plus.google.com/$your_username' %>
              <small class="error">Must be full URL, for example: http://google.com</small>
            </div>
          </div>
        </fieldset>
      </div>
    </div>

    <br/>

    <div class="row">
      <div class="large-4 columns actions" id="bio">
        <%= f.label :bio %>
        <%= f.text_area :bio, actionname: action_name %>
      </div>
    </div>

  <br/><br/>
    <div class="row">
      <div class="large-4 columns" id="notificationSettings">
        <table width="100%">
          <tr>
            <td>
              <div class="switch">
                <%= f.check_box :notify_instant, :checked => @user.notify_instant %>
                <%= f.label :notify_instant %>
              </div>
            </td>
            <td valign="top">
              <p style="padding-top: 5px;">Instant Email Notifications</p>
            </td>
          </tr>
          <tr>
            <td>
              <div class="switch">
                <%= f.check_box :notify_daily, :checked => @user.notify_daily %>
                <%= f.label :notify_daily %>
              </div>
            </td>
            <td valign="top">
              <p style="padding-top: 5px;">Daily Email Digest</p>
            </td>
          </tr>
          <tr>
            <td>
              <div class="switch">
                <%= f.check_box :notify_weekly, :checked => @user.notify_weekly %>
                <%= f.label :notify_weekly %>
              </div>
            </td>
            <td valign="top">
              <p style="padding-top: 5px;">Weekly Email Digest</p>
            </td>
          </tr>
        </table>
      </div>

    </div>
    <br/>  <br/>

  <div class="row">
      <div class="large-4 columns actions">
        <%= button_tag type: 'submit', class: 'button small success' do %>
            <%= image_tag 'save-icon.svg', class: 'ty-icon' %>
            &nbsp;
            Update Profile
        <% end %>
      </div>
    </div>

<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

  <div class="row">
    <div class="columns large-4">
      <% flash.each do |type, message| %>
        <div class="flash alert-box text-center <%= type %>", role="dialogalert", data-alert>
          <%= message %>
          <a href="#" class="close">&times;</a>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="columns large-4">
      <%= f.text_field :email, placeholder: 'Email' %>
    </div>
  </div>

  <div class="row">
    <div class="columns large-4">
      <%= f.password_field :password, placeholder: 'Password' %>
    </div>
  </div>

  <div class="row">
    <div class="columns large-4">
      <%= f.submit 'Register', :class => 'button small success' %>
    </div>
  </div>

<% end %>

app/views/users/edit.html.erb
<div class="small-12 large-12 columns">

<h3>Edit Profile</h3>
<ul class="tabs" data-tab>
  <li class="tab-title active"><a href="#settings">Settings</a></li>
  <li class="tab-title" id="changePassowrd"><a href="#cp">Change Password</a></li>
</ul>
<div class="tabs-content">
  <div class="content active" id="settings">
    <%= render 'edit_form' %>
  </div>
  <div class="content" id="cp">
    <%= render 'change_password_form' %>
  </div>
</div>


<%= link_to 'Cancel', user_path(@user) %>
<br/><br/>

<% if current_user == @user || (current_user && current_user.admin?) %>
    <h5><small>
      <%= link_to 'Delete Account', @user, method: :delete,
                  data: { confirm: 'Are you sure?' },
                  class: 'delete' %>
    </small></h5>
<% end %>

<br/><br/>
</div>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>ID #</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Username</th>
      <th>Created At</th>
      <th>Facebook ID</th>
      <th>Twitter ID</th>
      <th>Google ID</th>
      <th colspan="">Functions</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.username %></td>
        <td><%= user.created_at %></td>
        <td><%= user.facebook_id %></td>
        <td><%= user.twitter_id %></td>
        <td><%= user.google_id %></td>
        <td>
          <%= link_to 'Show', user %>
          <br/><br/>
          <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %>
          <br/><br/>
          <% if user.admin? %>
            <%= link_to 'Admin!', '/remove_admin/' + user.id.to_s, method: :delete %>
        <% else %>
              <%= link_to 'Admin?', add_admin_path(user), method: :put %>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br/><br/>

app/views/users/new.html.erb
<div class="small-12 large-12 columns">
  <div class="large-12 main-video columns">
    <video autoplay loop id="bgvid">
      <source src="/videos/bcn_movie-2.mp4" type="video/mp4">
    </video>
  </div>

  <div class="intro">
    <h4>Do you have one of these Social accounts?</h4>

    <div id="socialRegisters">
      <%= link_to "Register with Facebook", '/auth/facebook', :class => 'button small facebook' %>


      <%= link_to "Register with Twitter", '/auth/twitter', :class => 'button small twitter', :id => 'twitter_login' %>


      <%= link_to "Register with Google", '/auth/google_oauth2', :class => 'button small google', :id => 'google_login' %>
    </div>


    <hr/>
    <p>Or</p>

    <h4>Register With Email</h4>

    <%= render 'form' %>
  </div>

  <br/><br/>
</div>