config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  get 'home', to: 'home#home'
  get 'help', to: 'home#help'
  get 'contact', to: 'home#contact'
  post 'send_contact', to: 'home#send_contact'
  get 'about', to: 'home#about'
  get 'calendar', to: 'home#calendar'

  resources :communities do
    patch 'organizations', to: 'communities#add_member'
    delete 'organizations', to: 'communities#remove_member', as: 'remove_organization'
    get :podcast, to: 'communities#podcast'
    resources :subscribers, only: [:create, :destroy]
  end

  resources :organizations do
    patch 'users', to: 'organizations#add_user'
    delete 'users', to: 'organizations#remove_user'
    resources :roles, only: [:update]
    get :podcast, to: 'organizations#podcast'
    resources :subscribers, only: [:create, :destroy]
  end

  resources :posts do
    resources :locations
    resources :comments, only: [:create]
    resources :subscribers, only: [:create, :destroy]
    delete 'community', to: 'posts#remove_community'
    get :autocomplete_community_name, on: :collection
    get :get_og_data, on: :collection
  end

  get :events, to: 'posts#events', as: 'events'

  resources :comments, only: [:update, :destroy, :show] do
    resources :comments, only: [:create, :update, :destroy]
  end

  resources :searches, only: [:index]

  #resources :facebook_subscriptions, only: [:index, :create]
  get '/facebook_subscriptions', to: 'facebook_subscriptions#index', as: 'facebook_subscriptions'
  post '/facebook_subscriptions/', to: 'facebook_subscriptions#create'
  resources :badges

  resources :photos, only: [:index, :new, :create, :destroy]
  resources :audios, only: [:index, :destroy]

  get '/login' => 'user_sessions#new', as: :login
  get '/logout' => 'user_sessions#destroy', as: :logout
  resources :user_sessions, only: [:create, :new]
  resources :users
  resources :password_resets, only: [:new, :create, :edit, :update]
  get :send_merge, to: 'users#send_merge_email'
  get :merge_user, to: 'users#merge_user'
  put '/add_admin/:user_id', to: 'users#add_admin', as: 'add_admin'
  delete '/remove_admin/:user_id', to: 'users#remove_admin', as: 'remove_admin'


  get 'locations', to: 'locations#show'

  namespace :api do
    resources :posts do
      resources :locations, only: [:create, :update, :destroy]
      resources :communities, only: [:create, :update, :destroy]
      resources :subscribers, only: [:create, :destroy]
      resources :comments, only: [:create]
    end
    get 'today', to: 'posts#today'
    get 'tomorrow', to: 'posts#tomorrow'
    get 'next_week', to: 'posts#next_week'
    get :events, to: 'posts#events', as: 'events'

    resources :comments, only: [:update, :destroy, :show] do
      resources :comments, only: [:create, :update, :destroy]
    end

    resources :communities do
      resources :posts, only: [:create, :update, :destroy]
      resources :locations, only: [:create, :update]
      patch 'organizations', to: 'communities#add_member'
      delete 'organizations', to: 'communities#remove_member', as: 'remove_organization'
      resources :subscribers, only: [:create, :destroy]
    end

    resources :organizations do
      resources :posts, only: [:create, :update, :destroy]
      resources :locations, only: [:create, :update]
      patch 'users', to: 'organizations#add_user'
      delete 'users', to: 'organizations#remove_user'
      resources :subscribers, only: [:create, :destroy]
    end

    resources :locations, only: [:show, :create, :update, :destroy] do
      resources :posts, only: [:create, :update, :destroy]
    end

    resources :users do
      resources :posts, only: [:create, :update, :destroy]
    end

    resources :searches, only: [:index]
    resources :badges, only: [:index, :show]
  end

  get 'auth/facebook', as: 'auth_provider'
  get 'auth/facebook/callback', to: 'user_sessions#facebook_login'
  get 'auth/twitter', as: 'twitter_auth_provider'
  get 'auth/twitter/callback', to: 'user_sessions#twitter_login'
  get 'auth/google_oauth2', as: 'google_auth_provider'
  get 'auth/google_oauth2/callback', to: 'user_sessions#google_login'
  get 'auth/failure', to: 'user_sessions#auth_failure'


  root 'home#home'

  require 'sidekiq/web'
  require 'admin_constraint'
  mount Sidekiq::Web => '/kiq', :constraints => AdminConstraint.new
  # constraints lambda {|request| AuthConstraint.admin?(request) } do
  #   mount Sidekiq::Web => '/admin/kiq'
  # end

end

app/models/post.rb
class Post < ActiveRecord::Base
  include ActiveModel::Dirty

  acts_as_paranoid
  dragonfly_accessor :image
  dragonfly_accessor :audio

  attr_accessor :image_web_url, :audio_web_url

  validates :start_date, allow_nil: true, format: { with: /.*/, message: 'format must look like: 2015-05-25' }
  validates :start_time, allow_nil: true, format: { with: /.*/, message: 'format must look like 05:05' }
  validates :end_date, allow_nil: true, format: { with: /.*/, message: 'format must look like: 2015-05-25' }
  validates :end_time, allow_nil: true, format: { with: /.*/, message: 'format must look like 05:05' }
  validates :title, length: { in: 0..140 }, format: { without: /https?:\/\/[\S]+/, message: 'cannot be a URL.' }

  def not_url
    return title =~ /https?:\/\/[\S]+/
  end

  validates_property :ext, of: :image, in: ['jpeg', 'jpg', 'png', 'gif', 'svg', 'svgz'], if: :image_changed?
  validates_property :mime_type, of: :image,
                     in: ['image/jpeg', 'image/png', 'image/gif', 'image/svg+xml', 'image/svg'],
                     if: :image_changed?
  validates_property :format, of: :image, in: ['jpeg', 'png', 'gif', 'svg', 'svgz'], if: :image_changed?

  validates_property :ext, of: :audio,
                     in: ['mp3', 'ogg', 'wmv', 'm2a', 'midi', 'mpg', 'wav', 'mp4', 'm4a'],
                     if: :audio_changed?
  validates_property :mime_type, of: :audio, in: ['audio/mpeg', 'audio/ogg', 'audio/midi', 'audio/mpeg3', 'audio/wav',
                                                  'audio/mp4a-latm', 'application/ogg'], if: :audio_changed?


  belongs_to :user
  has_many :comments
  has_many :subscribers, :class_name => "Subscriber", :foreign_key => "post_id"
  has_many :photos
  has_many :audios
  has_and_belongs_to_many :communities
  has_and_belongs_to_many :locations
  belongs_to :organization

  before_save :set_audio_duration

  def as_json(options={})
    if self.image
      self.image_web_url = self.image.url
    elsif self.og_image
      self.image_web_url = self.og_image
    end

    self.audio_web_url = self.audio.url if self.audio

    super(methods: [:image_web_url, :audio_web_url], :only => [
        :id,
        :title,
        :description,
        :start_date,
        :end_date,
        :image_web_url,
        :audio_web_url,
        :created_at
      ],
      :include => {
        :locations => {
          :only => [
            :id,
            :lat,
            :lon,
            :name,
            :address,
            :city,
            :state,
            :postcode,
            :county,
            :country
          ]
        },
        :communities => {
          :only => [
            :id,
            :name,
            :description,
            :home_page,
            :color
          ]
        },
        :organization => {
            :only => [
                :id,
                :name,
                :description,
                :home_page,
                :color
            ]
        },
        :user => {
            :only => [
                :id,
                :email,
                :first_name,
                :last_name,
                :username
            ]
        }
      }
    )
  end

  def get_og_attrs(url)

    data = {}
    begin
      doc = Nokogiri::HTML(open(url, 'User-Agent' => 'ruby'))

      doc.css('meta').each do |node|
        case node['property']
          when 'og:title'
            data[:og_title] = node['content']
          when 'og:image'
            data[:og_image] = node['content']
          when 'og:url'
            data[:og_url] = node['content']
          when 'og:description'
            data[:og_description] = node['content']
        end
        # Grab the rest of the attributes as best we can.
        unless data[:og_description]
          if node['name'] == 'description'
            data[:og_description] = node['content']
          end
        end
        data[:og_url] = url unless data[:og_url]
        data[:og_image] = '//:0' unless data[:og_image]
        data[:og_title] = doc.css('title').text unless data[:og_title]
      end
    rescue
      data[:og_error] = 'Sorry no preview available.'
      data[:og_url] = url
      data[:og_image] = '//:0'
      data[:og_title] = url
      data[:og_description] = ' '
    end
    data
  end

  def create_location(params)
    loc = Location.new.set_location_attrs(Location.new, params)
    self.locations << loc
  end

  def set_audio_duration
    require 'taglib'

    if audio
      file_path = Rails.root.join('public', 'system', 'dragonfly', Rails.env, audio_uid).to_s
      TagLib::FileRef.open(file_path) { |f| self.audio_duration = f.audio_properties.length }
    end
  end

  def set_image
    unless self.image
      self.image = self.photos[0].image if self.photos[0]
      self.save
    end
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < Api::ApiController
  before_filter :authenticate, only: [:create, :update, :destroy]

  def index
    posts = Post.where(start_date: nil).order('created_at DESC').paginate(:page => params[:page], :per_page => 6)
    render json: posts.as_json(include: :location)
  end

  def events
    case params[:events]
    when 'today'
      today = DateTime.now
      events = Post.where(['start_date between ? and ?', today.beginning_of_day, today.end_of_day]).order(:start_date).paginate(:page => params[:page], :per_page => 20)
    when 'tomorrow'
      tomorrow = DateTime.now + 1
      events = Post.where(['start_date between ? and ?', tomorrow.beginning_of_day, tomorrow.end_of_day]).order(:start_date).paginate(:page => params[:page], :per_page => 20)
    when 'next_week'
      events = Post.where(start_date: Time.now.next_week..Time.now.next_week.end_of_week).order(:start_date).paginate(:page => params[:page], :per_page => 20)
    else
      events = Post.where(['start_date = ? or start_date > ?', DateTime.now, DateTime.now]).order(:start_date).paginate(:page => params[:page], :per_page => 20)
    end
    render json: events.as_json(include: :location)
  end

  def show
    post = Post.find(params[:id])
    render json: post.as_json(include: :locations)
  end

  def today
    @posts = Post.where(start_date: Date.today)
    render json: @posts.as_json
  end

  def tomorrow
    @posts = Post.where(start_date: Date.tomorrow)
    render json: @posts.as_json
  end

  def next_week
    @posts = Post.where(start_date: Time.now.next_week..Time.now.next_week.end_of_week)
    render json: @posts.as_json
  end

  def create
    if post_params['lat'] and post_params['lon']
      lat = params[:post].delete :lat
      lon = params[:post].delete :lon
    end

    if current_user
      post = current_user.posts.new(post_params)
    else
      post = Post.new(post_params)
    end
    post.create_location({lat: lat, lon: lon}) if lat and lon

    if post.save

      # Notify Community subscribers.
      unless post.communities.blank?
        if current_user
          current_user.username.nil? ? poster = 'Anonymous' : poster = current_user.username
          ApplyBadgesJob.perform_now(current_user)

        else
          poster = 'Anonymous'
        end
        post.communities.each do |community|
          community.subscribers.each do |subscriber|
            unless current_user == subscriber.user
              if subscriber.user.notify_instant
                PostMailer.new_post(subscriber.user, post, community, poster).deliver_now
              end
            end
          end
        end
      end

      # Add the Organization's Communitites and Location if posting as an Org.
      if post.organization
        if post.organization.location
          post.locations << post.organization.location
        end
        unless post.organization.communities.blank?
          post.communities << post.organization.communities
        end
        post.save
      end

      render status: 200, json: {
        message: 'Post created.',
        post: post,
        locations: post.locations
      }.to_json
    else
      render status: 422, json: {
        errors: post.errors
      }.to_json
    end
  end

  def update
    begin
      post = current_user.posts.find(params[:id])

      message = 'Post updated.'
      if params[:community_id]
        post.communities << Community.find(params[:community_id])
        message = 'Community added to Post.'
      end

      if post.update(post_params)
        render status: 200, json: {
                              message: message,
                              post: post,
                              locations: post.locations,
                              communities: post.communities
                          }.to_json
      else
        render status: 422, json: {
                              message: 'Post could not be updated.',
                              post: post
                          }.to_json
      end
    rescue
      render status: 404, json: {
                            message: 'Only post creator can update it.',
                            post: post
                        }.to_json
    end
  end

  def destroy
    post = current_user.posts.find(params[:id])

    message = 'Post deleted.'
    if params[:community_id]
      post.communities.delete(Community.find(params[:community_id]))
      message = 'Community removed from Post.'
    else
      post.destroy
    end

    render status: 200, json: {
      message: message
    }.to_json
  end

  private
  def post_params
    params.require('post').permit(:title,
                                  :description,
                                  :lat,
                                  :lon,
                                  :location_id,
                                  :user_id,
                                  :start_date,
                                  :start_time,
                                  :end_date,
                                  :end_time,
                                  :image,
                                  :audio,
                                  :community_names,
                                  :og_url,
                                  :og_image,
                                  :og_title,
                                  :og_description,
                                  :community_ids => [])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def post_list_image(post)

    if params[:community] && @community
      border = "border: 5px solid #{@community.color}"
    elsif post.organization
      border = "border: 5px solid #{post.organization.color}"
    else
      border = ''
    end

    if post.image
      link_to post do
        image_tag post.image.thumb('75x75#').url, style: border
      end
    elsif post.og_image && post.og_image != '//:0' && !post.og_image.blank?
      link_to post do
       image_tag post.og_image, style: border
      end
    elsif post.start_date
      link_to post do
        image_tag 'calendar-icon.svg', size: '75x75', alt: post.title, style: border
      end
     else
      link_to post do
        image_tag 'bcn_logo_black.svg', size: '75x75', alt: post.title, style: border
       end
    end
  end

  def sortable(title, column, type)
    if (type == 'events')
      path = events_path
    else
      path = posts_path
    end

    path = path + "?sort=#{column}"

    color = sort_column == column ? 'secondary' : ''

    link_to path, class: "button small #{color}", id: column do
      "#{title}".html_safe
    end
  end
end

app/views/posts/_new_comment_form.html.erb
<div class="hidden <%= dom_id(comment) %>_new">
  <p>Reply:</p>
  <%= form_tag comment_comments_path(comment), :enctype => "multipart/form-data", :class => 'comment' do %>
    <div class="row">
      <div class="large-12 columns actions">
        <%= image_tag 'avatar.png', class: 'hidden image_to_upload' %>

        <%= label_tag :photo, 'Add a pic?'%>
        <%= file_field_tag 'comment[photo]', class: 'photo_upload' %>
        <%= hidden_field_tag :retained_photo %>

        <%= text_area_tag 'comment[content]', '', :id => 'content_' + dom_id(comment) %>

        <% if current_user && !current_user.organizations.blank? %>
          <div>
            <label for="commentor">Comment As:</label>
            <select name="comment[organization_id]" id="post_organization">
              <option value=""></option>
              <% current_user.organizations.each do |organization| %>
                <option value="<%= organization.id %>"><%= organization.name %></option>
              <% end %>
            </select>
          </div>
        <% end %>
      </div>
    </div>

    <div class="row">
      <div class="large-12 columns actions">
        <%= button_tag type: 'submit', class: 'button small success', id: "save_#{dom_id(comment)}" do %>
          <%= image_tag 'save-icon.svg', class: 'ty-icon' %>
          &nbsp;
          Save Comment
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<div class="small-12 large-12 columns">

  <h2>Editing Post: <span class='title'><%= @post.title %></span></h2>

  <%= render 'form' %>

  <%= link_to 'Delete', @post, method: :delete, :class => 'delete', data: { confirm: 'Are you sure?' } %>

  <br/><br/>
</div>

app/views/posts/new.html.erb
<div class="small-12 large-12 columns">
  <h1>New Post</h1>

  <%= render 'form' %>

  <br/><br/>
</div>

app/views/posts/show.html.erb
<%= content_for(:title) do %>
  <% unless @post.title.blank? %>
    <%= @post.title %> |
  <% else %>
    Post |
  <% end %>
<% end %>
<%= content_for(:meta_og) do %>
  <meta property="og:title" content="<%= @post.title %>" />
  <meta property="og:type" content="article" />
  <meta property="og:published_time" content="<%= @post.created_at.strftime('%Y-%m-%d %H:%M') %>" />
  <meta property="og:author" content="<%= @post.user.username if @post.user && @post.user.username %>" />
  <% if @post.description %>
    <meta property="og:description" content="<%= truncate(strip_tags( markdown(@post.description) ), length: 50) %>" />
  <% end %>
  <% if @post.image %>
    <%= tag :meta, property: 'og:image', content: "http://#{request.host}#{@post.image.url}" %>
  <% end %>
  <meta property="fb:app_id" content="<%= FACEBOOK_CONFIG['app_id'] %>" />
<% end %>


<div class="row">

  <div class="large-8 columns">
    <div class="post-content">
      <h2 class="title">
        <%= @post.title %>
      </h2>
      <div class="row">
        <div class="large-12 columns no-left-padding">
          <% if @post.image %>
            <%= image_tag @post.image.url, class: 'post-image', data: { action: 'zoom' } %>
          <% end %>
          <br/><br/>
        </div>
      </div>

      <div class="row">
        <div class="large-12 columns shadow-list text-block">
          <%= markdown(@post.description) if @post.description %>
        </div>
      </div>
      <br/><br/>

      <% unless @post.audios.empty? %>
        <ul class="no-bullet audio-list">
          <% @post.audios.each do |audio| %>
            <li>
              <strong><%= audio.audio.name %></strong>
              <br/>
              <%= audio_tag audio.audio.url, controls: true, preload: 'none' %>

              &nbsp;&nbsp;&nbsp;&nbsp;

              <%= link_to audio.audio.url, class: 'button tiny success' do %>
                <%= image_tag 'download-icon.svg', class: 'ty-icon' %> &nbsp;
                Download <%= audio.audio.name[0..-5] %>
              <% end %>
            </li>
          <% end %>
        </ul>
      <% end %>

      <div class="row post-second-row">
        <div class="large-9 columns">
          <% unless @post.og_url.blank? %>
            <div class="row og-row">
              <div class="large-4 columns og-data">
                <%= link_to @post.og_url, class: 'og-url', target: '_blank' do %>
                  <%= image_tag @post.og_image, class: 'og-image' %>
                  <h5 class="og-title"><%= @post.og_title %></h5>
                  <p class="og-description"><%= @post.og_description %> </p>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <div class="row social-row">
        <div class="large-3 columns social-share right">
          <% if @post.description %>
            <%= link_to "https://twitter.com/intent/tweet?url=#{request.original_url}&text=#{truncate( strip_tags( markdown(@post.description) ), length: 25)}&hashtags=boone,bcn",
                        target: '_blank', class: 'button sm-icon info share' do %>
              <%= image_tag 'twitter-icon-white.svg', class: 'sm-icon' %>
            <% end %>
          <% end %>

          <%= link_to "http://www.facebook.com/sharer.php?u=#{request.original_url}&title=#{@post.title}",
                      target: '_blank', class: 'button sm-icon info share' do %>
            <%= image_tag 'facebook-icon-white.svg', class: 'sm-icon' %>
          <% end %>
          <%= link_to "https://plus.google.com/share?url=URL=#{request.original_url}",
                      target: '_blank', class: 'button sm-icon info share' do %>
            <%= image_tag 'google-icon-white.svg', class: 'sm-icon' %>
          <% end %>
        </div>
      </div>

    </div>

    <hr/>

    <div class="row">
      <div class="large-4 columns right post-meta-container">
        <div class="post-meta right">
          <%= render 'post_sig' %>
        </div>

        <div class="post-edit">

          <% if @post.user == current_user || (current_user && current_user.admin?) %>
            <%= link_to edit_post_path(@post), class: 'button tiny icon post-edit-link', title: 'Edit Post' do %>
              <%= image_tag 'edit-icon.svg', class: 'icon' %>
            <% end %>
          <% end %>
        </div>


        <% if current_user && @post.user != current_user %>
          <% if current_user.subscriptions.find_by(post_id: @post.id) %>
            <%= link_to '#',
                        class: 'button tiny secondary icon post-subscribe',
                        title: 'Unsubscribe from Post',
                        data: { post_id: @post.id, current_user_id: current_user.id, status: 'subscribed' } do %>

              <%= image_tag 'tack-icon-green.svg', class: 'icon', title: 'Unsubscribe from Post' %>
            <% end %>
          <% else %>
            <%= link_to '#',
                        class: 'button tiny icon post-subscribe',
                        title: 'Subscribe to Post',
                        data: { post_id: @post.id, current_user_id: current_user.id, status: 'unsubscribed' } do %>
              <%= image_tag 'tack-icon.svg', class: 'icon', title: 'Subscribe to Post' %>
            <% end %>

          <% end %>
        <% end %>
      </div>

      <div class="large-8 columns left post-objects">
        <div class="post-attrs">

          <ul class="tabs" data-tab role="tablist">
            <li class="tab-title active" role="presentational" >
              <a href="#dates" role="tab" tabindex="0" aria-selected="true" controls="dates">Dates</a>
            </li>
            <li class="tab-title" role="presentational" >
              <a href="#locations" role="tab" tabindex="0" aria-selected="false" controls="locations">Locations</a>
            </li>
            <li class="tab-title" role="presentational">
              <a href="#communities" role="tab" tabindex="0" aria-selected="false" controls="communities">Communities</a>
            </li>
            <li class="tab-title" role="presentational">
              <a href="#gallery" role="tab" tabindex="0" aria-selected="false" controls="gallery">Gallery</a>
            </li>
          </ul>
          <div class="tabs-content">
            <section role="tabpanel" aria-hidden="false" class="content active" id="dates">
              <% if @post.start_date %>
                <p>
                  <br/>
                  <em>Starting:</em>
                  <%= @post.start_date.strftime('%m/%d/%Y') %>
                  at
                  <%= @post.start_time.to_s(:time) if @post.start_time %>
                  <br/>
              <% end %>
              <% if @post.end_date %>
                <em>Ending:</em>
                <%= @post.end_date.strftime('%m/%d/%Y') %>
                at
                <%= @post.end_time.to_s(:time) if @post.end_time %>
                </p>
              <% end %>

              <% unless @post.start_date && @post.end_date %>
                <p class="grey">No dates set.</p>
              <% end %>
            </section>

            <section role="tabpanel" aria-hidden="true" class="content" id="locations">
              <% unless @post.locations.empty? %>
                <ul id="<%= dom_id(@post) %>" class="no-disc">
                  <% @post.locations.each do |location| %>
                    <li>
                          <span id="<%= dom_id(location) %>">
                            <strong><%= location.name %></strong>
                            <br/>
                            <span class="location-details">
                              <%= location.address %>
                              <%= location.city %>,
                              <%= location.state %>
                              <%= location.postcode %>
                            </span>
                          </span>

                      &nbsp;&nbsp;

                      <% if @post.user == current_user || (current_user && current_user.admin?) %>
                        <%= link_to post_location_path(@post.id, location.id),
                                    method: :delete,
                                    class: "button alert tiny remove_location icon",
                                    title: 'Remove Location',
                                    data: { confirm: 'Are you sure?' } do %>
                          <%= image_tag 'trash-icon.svg', class: 'icon' %>
                        <% end %>
                      <% end %>
                    </li>

                  <% end %>
                </ul>
              <% else %>
                <p class="grey" id="no-locations">No locations set.</p>
              <% end %>
            </section>

            <section role="tabpanel" aria-hidden="true" class="content" id="communities">
              <% unless @post.communities.empty? %>
                <ul class="communities no-disc">
                  <% @post.communities.each do |community| %>
                    <%= render 'layouts/communities_list', community: community %>
                  <% end %>
                </ul>
              <% else %>
                <p class="grey">No communities set.</p>
              <% end %>
            </section>
            <section role="tabpanel" aria-hidden="true" class="content" id="gallery">
              <% if not @gallery.empty? %>
                <ul class="gallery clearing-thumbs small-block-grid" data-clearing>
                  <% if @post.image %>
                    <li><a href="<%= @post.image.url %>" class="th"><img src="<%= @post.image.url %>" width="120"></a></li>
                  <% end %>

                  <% if @post.photos %>
                    <% @post.photos.each do |photo| %>
                      <li><a href="<%= photo.image.url %>" class="th"><img src="<%= photo.image.url %>" width="120"></a></li>
                    <% end %>
                  <% end %>

                  <% @gallery.each do |image| %>
                    <li><a href="<%= image %>" class="th"><img src="<%= image %>" width="120"></a></li>
                  <% end %>
                </ul>
              <% elsif not @post.photos.empty? %>
                <ul class="gallery clearing-thumbs small-block-grid" data-clearing>
                    <% @post.photos.each do |photo| %>
                      <li><a href="<%= photo.image.url %>" class="th"><img src="<%= photo.image.url %>" width="120"></a></li>
                    <% end %>
                </ul>
              <% else %>
                <p class="grey">No pictures uploaded... yet.</p>
              <% end %>
            </section>
          </div>
        </div>
      </div>

    </div>
  </div>

  <div class="large-3 columns map-container">
    <div class="row">
      <div class="large-12">
        <div class="org-link">
          <% if @post.organization %>
            <%= link_to @post.organization do %>
              <%= image_tag @post.organization.image.url, width: '150' if @post.organization.image %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="large-12">
        <%= button_tag class: 'button tiny secondary expand-map' do %>
          <%= image_tag 'expand-icon.svg', class: 'ty-icon' %> &nbsp;
          Expand Map
        <% end %>
        <%= button_tag class: 'button tiny secondary contract-map hidden' do %>
          <%= image_tag 'contract-icon.svg', class: 'ty-icon' %> &nbsp;
          Shrink Map
        <% end %>
        <div id="map" class="post-map"></div>
      </div>
    </div>

  </div>
</div>

<div class="row">
  <div class="large-12 columns">
    <a class="button tiny toggle comment-button" data-toggle="post-comment">
      <%= image_tag 'reply-icon-white.svg', class: 'ty-icon toggle', data: { toggle: "post-comment" } %> &nbsp;
      Comment?
    </a>

    <div class="hidden post-comment">
      <%= form_tag post_comments_path(@post), :enctype => "multipart/form-data", :class => 'comment' do %>
        <div class="row">
          <div class="large-4 columns actions">
            <%= image_tag 'avatar.png', class: 'hidden image_to_upload' %>

            <%= label_tag :photo, 'Add a pic?'%>
            <%= file_field_tag 'comment[photo]', class: 'photo_upload' %>
            <%= hidden_field_tag :retained_photo %>

            <%= text_area_tag 'comment[content]' %>

            <% if current_user && !current_user.organizations.blank? %>
              <div>
                <label for="commentor">Comment As:</label>
                <select name="comment[organization_id]" id="post_organization">
                  <option value=""></option>
                  <% current_user.organizations.each do |organization| %>
                    <option value="<%= organization.id %>"><%= organization.name %></option>
                  <% end %>
                </select>
              </div>
            <% end %>

          </div>
        </div>

        <div class="row">
          <div class="large-4 columns actions">
            <%= button_tag type: 'submit', class: 'button small success save-comment' do %>
              <%= image_tag 'save-icon.svg', class: 'ty-icon' %>
              &nbsp;
              Save Comment
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<br/>
<div class="row">
  <div class="large-12 columns comments">
    <% if @post.comments %>
      <%= render 'comments', {comments: @post.comments} %>
    <% end %>
  </div>
</div>


<br/><br/>