config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  get 'home', to: 'home#home'
  get 'help', to: 'home#help'
  get 'contact', to: 'home#contact'
  post 'send_contact', to: 'home#send_contact'
  get 'about', to: 'home#about'
  get 'calendar', to: 'home#calendar'

  resources :communities do
    patch 'organizations', to: 'communities#add_member'
    delete 'organizations', to: 'communities#remove_member', as: 'remove_organization'
    get :podcast, to: 'communities#podcast'
    resources :subscribers, only: [:create, :destroy]
  end

  resources :organizations do
    patch 'users', to: 'organizations#add_user'
    delete 'users', to: 'organizations#remove_user'
    resources :roles, only: [:update]
    get :podcast, to: 'organizations#podcast'
    resources :subscribers, only: [:create, :destroy]
  end

  resources :posts do
    resources :locations
    resources :comments, only: [:create]
    resources :subscribers, only: [:create, :destroy]
    delete 'community', to: 'posts#remove_community'
    get :autocomplete_community_name, on: :collection
    get :get_og_data, on: :collection
  end

  get :events, to: 'posts#events', as: 'events'

  resources :comments, only: [:update, :destroy, :show] do
    resources :comments, only: [:create, :update, :destroy]
  end

  resources :searches, only: [:index]

  #resources :facebook_subscriptions, only: [:index, :create]
  get '/facebook_subscriptions', to: 'facebook_subscriptions#index', as: 'facebook_subscriptions'
  post '/facebook_subscriptions/', to: 'facebook_subscriptions#create'
  resources :badges

  resources :photos, only: [:index, :new, :create, :destroy]
  resources :audios, only: [:index, :destroy]

  get '/login' => 'user_sessions#new', as: :login
  get '/logout' => 'user_sessions#destroy', as: :logout
  resources :user_sessions, only: [:create, :new]
  resources :users
  resources :password_resets, only: [:new, :create, :edit, :update]
  get :send_merge, to: 'users#send_merge_email'
  get :merge_user, to: 'users#merge_user'
  put '/add_admin/:user_id', to: 'users#add_admin', as: 'add_admin'
  delete '/remove_admin/:user_id', to: 'users#remove_admin', as: 'remove_admin'


  get 'locations', to: 'locations#show'

  namespace :api do
    resources :posts do
      resources :locations, only: [:create, :update, :destroy]
      resources :communities, only: [:create, :update, :destroy]
      resources :subscribers, only: [:create, :destroy]
      resources :comments, only: [:create]
    end
    get 'today', to: 'posts#today'
    get 'tomorrow', to: 'posts#tomorrow'
    get 'next_week', to: 'posts#next_week'
    get :events, to: 'posts#events', as: 'events'

    resources :comments, only: [:update, :destroy, :show] do
      resources :comments, only: [:create, :update, :destroy]
    end

    resources :communities do
      resources :posts, only: [:create, :update, :destroy]
      resources :locations, only: [:create, :update]
      patch 'organizations', to: 'communities#add_member'
      delete 'organizations', to: 'communities#remove_member', as: 'remove_organization'
      resources :subscribers, only: [:create, :destroy]
    end

    resources :organizations do
      resources :posts, only: [:create, :update, :destroy]
      resources :locations, only: [:create, :update]
      patch 'users', to: 'organizations#add_user'
      delete 'users', to: 'organizations#remove_user'
      resources :subscribers, only: [:create, :destroy]
    end

    resources :locations, only: [:show, :create, :update, :destroy] do
      resources :posts, only: [:create, :update, :destroy]
    end

    resources :users do
      resources :posts, only: [:create, :update, :destroy]
    end

    resources :searches, only: [:index]
    resources :badges, only: [:index, :show]
  end

  get 'auth/facebook', as: 'auth_provider'
  get 'auth/facebook/callback', to: 'user_sessions#facebook_login'
  get 'auth/twitter', as: 'twitter_auth_provider'
  get 'auth/twitter/callback', to: 'user_sessions#twitter_login'
  get 'auth/google_oauth2', as: 'google_auth_provider'
  get 'auth/google_oauth2/callback', to: 'user_sessions#google_login'
  get 'auth/failure', to: 'user_sessions#auth_failure'


  root 'home#home'

  require 'sidekiq/web'
  require 'admin_constraint'
  mount Sidekiq::Web => '/kiq', :constraints => AdminConstraint.new
  # constraints lambda {|request| AuthConstraint.admin?(request) } do
  #   mount Sidekiq::Web => '/admin/kiq'
  # end

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  acts_as_paranoid
  has_secure_password
  dragonfly_accessor :image

  validates :web_url, allow_nil: true, allow_blank: true, format: { with: /(https?|ftp|file|ssh):\/\// }
  validates :facebook_link, allow_nil: true, allow_blank: true, format: { with: /(https?|ftp|file|ssh):\/\// }
  validates :twitter_link, allow_nil: true, allow_blank: true, format: { with: /(https?|ftp|file|ssh):\/\// }
  validates :google_link, allow_nil: true, allow_blank: true, format: { with: /(https?|ftp|file|ssh):\/\// }

  validates_property :mime_type, of: :image,
                     in: ['image/jpeg', 'image/png', 'image/gif', 'image/svg+xml', 'image/svg', 'application/octet-stream'],
                     if: :image_changed?
  validates_property :format, of: :image, in: ['jpeg', 'png', 'gif', 'svg', 'svgz'], if: :image_changed?

  has_and_belongs_to_many :communities
  has_many :posts
  has_and_belongs_to_many :users
  has_many :comments
  has_many :subscribers, :class_name => "Subscriber", :foreign_key => "organization_id"
  has_many :facebook_subscriptions
  has_many :roles
  has_one :location

  before_save :set_slug
  before_update :set_slug

  def to_param
    slug
  end

  def set_slug
    # Remove non-alphanumeric characters, but leave spaces.  Then replaces spaces with '-'.
    self.slug = name.downcase.gsub(/[^a-z0-9\s]/i, '').gsub(' ', '-').gsub('.', '')
  end

  def create_location(params)
    loc = Location.new.set_location_attrs(Location.new, params)
    self.location = loc
  end

  def as_json(options={})
    super(:only => [
              :id,
              :name,
              :description,
              :email,
              :created_at,
              :created_by,
              :facebook_link,
              :twitter_link,
              :google_link,
              :web_url,
              :image_name,
              :image_url,
              :color,
              :slug
          ], :include => {
             :location => {
                 :only => [
                     :id,
                     :lat,
                     :lon,
                     :name,
                     :address,
                     :city,
                     :state,
                     :postcode,
                     :county,
                     :country
                 ]
             },
           })
  end
end

app/controllers/api/organizations_controller.rb
class Api::OrganizationsController < Api::ApiController
  before_filter :authenticate, only: [:create, :update, :destroy, :add_user, :remove_user]

  def index
    organizations = Organization.all
    render json: organizations.as_json
  end

  def show
    organization = Organization.find_by_slug(params[:id])
    render json: organization.as_json(include: :posts)
  end

  def create
    organization = current_user.organizations.new(organization_params)
    organization.created_by = current_user.id
    if organization.save
      render status: 200, json: {
                            message: 'Organization created.',
                            organization: organization,
                        }.to_json
    else
      render status: 422, json: {
                            errors: organization.errors
                        }.to_json
    end
  end

  def update
    organization = Organization.find(params[:id])

    message = 'Organization updated.'
    if params[:post_id]
      organization.posts << Post.find(params[:post_id])
      message = 'Post added to organization.'
    end

    if organization.created_by == current_user.id

      if organization.update(organization_params)
        render status: 200, json: {
                              message: message,
                              organization: organization,
                              posts: organization.posts
                          }.to_json
      else
        render status: 422, json: {
                              message: 'organization could not be updated.',
                              post: post
                          }.to_json
      end
    else
      render status: 401, json: {
                            message: 'Only the organization creator and update the organization.',
                            organization: organization
                        }.to_json
    end
  end

  def add_user
    organization = Organization.find(params[:organization_id])

    if current_user.id == params['user_id'].to_i
      if Role.create(name: 'pending', user: current_user, organization: organization)
        Notifier.user_join(current_user, organization).deliver_now
        ApplyBadgesJob.perform_now(current_user)
        render status: 200, json: {
                              message: "Your membership request to #{@organization.name} has been submitted.",
                              organization: organization,
                          }.to_json
      end
    end
  end

  def remove_user
    organization = Organization.find(params[:organization_id])
    user = User.find(organization_params['user_ids'][0].to_i)

    if current_user.id == organization_params['user_ids'][0].to_i
      if organization.users.delete(user)
        render status: 200, json: {
                              message: 'User removed to organization.',
                              organization: organization,
                          }.to_json
      else
        render status: 422, json: {
                              message: 'User could not be removed to organization.',
                              organization: organization
                          }.to_json
      end
    else
      render status: 401, json: {
                            message: 'You can only remove yourself from a organization.',
                        }.to_json
    end
  end

  def destroy
    organization = Organization.find(params[:id])

    message = 'organization deleted.'
    if params[:post_id]
      organization.posts.delete(Post.find(params[:post_id]))
      message = 'Post removed from organization.'
    else
      organization.destroy
    end

    render status: 200, json: {
                          message: message
                      }.to_json
  end

  private
  def organization_params
    params.require('organization').permit(:name,
                                       :description,
                                       :home_page,
                                       :color,
                                       :events_url,
                                       :image,
                                       :created_by,
                                       :facebook_link,
                                       :twitter_link,
                                       :google_link,
                                       :user_ids => [])
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, except: [:index, :new, :create]
  before_action :require_user, except: [:index, :show]

  def show
    @posts = @organization.posts.order('created_at DESC').paginate(:page => params[:page], :per_page => 10)
  end

  def podcast
    @user = User.find(@organization.created_by)
    respond_to do |format|
      format.rss { render :layout => false }
    end
  end

  def index
    @organizations = Organization.all
  end

  def new
    @organization = Organization.new
  end

  def create
    if organization_params[:lat] and organization_params[:lon]
      lat = params[:organization].delete :lat
      lon = params[:organization].delete :lon
    end

    @organization = Organization.new(organization_params)
    @organization.password = (0...50).map { ('a'..'z').to_a[rand(26)] }.join
    @organization.created_by = current_user.id
    @organization.users << current_user

    if lat and lon
      @organization.create_location({lat: lat, lon: lon})
    else
      @organization.location = nil
    end

    if @organization.save
      role = Role.create(name: 'leader', user: current_user, organization: @organization)
      current_user.roles << role
      current_user.save

      FacebookFindGroupJob.perform_now(current_user.facebook_token, current_user, @organization) if current_user.facebook_token

      flash[:success] = 'Organization created.'
      redirect_to @organization
    else
      flash[:alert] = 'There was a problem creating the organization.'
      redirect_to new_organization_path
    end
  end

  def edit
    @roles = Role.where(organization: @organization.id)
    org_role = current_user.roles.find_by_organization_id(@organization.id)
    unless org_role && org_role.name == 'leader'
      redirect_to @organization, notice: 'Must be the creator of the organization to update it.'
    end
  end

  def update
    if (organization_params[:lat] && organization_params[:lon]) &&
        (!organization_params[:lat].blank? && !organization_params[:lon].blank?)
      lat = params[:organization].delete :lat
      lon = params[:organization].delete :lon
      @organization.create_location({lat: lat, lon: lon})
    else
      lat = params[:organization].delete :lat
      lon = params[:organization].delete :lon
    end

    if @organization.update(organization_params)
      flash[:success] = 'Organization updated.'
      redirect_to @organization
    else
      flash[:alert] = 'There was a problem updating the organization.'
      redirect_to :edit
    end
  end

  def destroy
    if @organization.destroy
      flash[:success] = 'Organization deleted.'
      redirect_to organizations_path
    else
      flash[:alert] = 'There was a problem deleting the organization.'
      redirect_to @organization
    end
  end

  def add_user
    if current_user.id == params['user_id'].to_i
      if Role.create(name: 'pending', user: current_user, organization: @organization)
        ApplyBadgesJob.perform_now(current_user)
        Notifier.user_join(current_user, @organization).deliver_now
        flash[:success] = "Your membership request to #{@organization.name} has been submitted."
        redirect_to @organization
      end
    end
  end

  def remove_user
    if current_user.id == params['user_id'].to_i || current_user.admin?
      @user = current_user
      if @organization.users.delete(current_user)
        flash[:success] = "You have left #{@organization.name}."
        redirect_to @user
      else
        redirect_to @user, notice: 'There was a problem leaving the organization.'
      end
    else
      redirect_to @user, notice: 'You can only remove yourself from a organization.'
    end
  end

  private
  def set_organization
    @organization = Organization.find_by_slug(params[:id]) if params[:id]
    @organization = Organization.find(params[:organization_id]) if params[:organization_id]
    @creator = User.find(@organization.created_by) if @organization.created_by
    @leaders = Role.where(organization: @organization, name: 'leader').collect { |u| u.user }
    @members = Role.where(organization: @organization, name: 'member').collect { |u| u.user }
    @penders = Role.where(organization: @organization, name: 'pending').collect { |u| u.user }
  end

  def organization_params
    params.require(:organization).permit(:name,
                                         :email,
                                         :description,
                                         :web_url,
                                         :image,
                                         :events_url,
                                         :color,
                                         :retained_image,
                                         :facebook_link,
                                         :twitter_link,
                                         :google_link,
                                         :lat,
                                         :lon

    )
  end
end

app/views/organizations/_form.html.erb
<ul class="tabs" data-tab>
  <li class="tab-title active <%= 'hide' if action_name == 'new' %>"><a href="#settings">Settings</a></li>
  <% if action_name == 'edit' %>
    <li class="tab-title"><a href="#members">Members</a></li>
  <% end %>
</ul>

<div class="tabs-content">
  <div class="content active" id="settings">
    <%= form_for(@organization) do |f| %>

      <% if @organization.errors.any? %>
        <div id="error_explanation" class="alert-box alert radius">
          <h5><%= pluralize(@organization.errors.count, "error") %> prohibited this post from being saved:</h5>

          <ul>
            <% @organization.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="row">
        <div class="large-4 columns">
          <fieldset>
            <legend>Details</legend>

            <div class="row">
              <div class="large-12 columns">
                <%= f.text_field :name, placeholder: :name, autofocus: 'autofocus', actionname: action_name %>
              </div>
            </div>

            <div class="row">
              <div class="large-12 columns">
                <%= f.text_field :color, placeholder: :color, actionname: action_name %>
              </div>
            </div>

            <div class="row">
              <div class="large-12 columns">

                <div class="row collapse">
                  <div class="small-10 columns">
                    <%= text_field_tag 'Default Location', '', placeholder: 'Default Location',
                                       class: 'new-location' %>
                  </div>
                  <div class="small-2 columns">
                    <a href="#" class="button postfix location-button">Search</a>
                  </div>
                </div>
              </div>
            </div>

          </fieldset>
        </div>
      </div>

      <div class="row map-row hidden">
        <div class="large-4 columns">
          <fieldset>
            <legend>Location</legend>
            <div class="map-container">
              <div id="map" class="new-map"></div>
            </div>
          </fieldset>
        </div>
      </div>

      <div class="row">
        <div class="large-4 columns" id="orgDescription">
          <%= f.label :description %>
          <%= f.text_area :description, placeholder: :description %>
        </div>
      </div>

      <div class="row">
        <div class="large-4 columns">
          <fieldset>
            <legend>Web Links</legend>

            <div class="row">
              <div class="large-12 columns">

                <%= f.text_field :web_url, placeholder: 'http://organization_website', actionname: action_name %>
              </div>
            </div>

            <div class="row">
              <div class="large-12 columns">
                <%= f.text_field :facebook_link, placeholder: 'http://facebook_page', actionname: action_name %>
              </div>
            </div>

            <div class="row">
              <div class="large-12 columns">
                <%= f.text_field :twitter_link, placeholder: 'http://twitter_page' %>
              </div>
            </div>

            <div class="row">
              <div class="large-12 columns">
                <%= f.text_field :google_link, placeholder: 'http://google_plus_page', actionname: action_name %>
              </div>
            </div>

            <div class="row">
              <div class="large-12 columns">
                <%= f.text_field :events_url, placeholder: 'http://your_calendar_link', actionname: action_name %>
              </div>
            </div>

          </fieldset>
        </div>
      </div>


      <div class="row">
        <div class="large-4 columns">
          <fieldset>
            <legend>Upload Photo</legend>

            <div class="row">
              <div class="large-12 columns">
                <%= image_tag 'avatar.png', class: 'hidden image_to_upload' %>
                <br/><br/>

                <%= f.file_field :image, class: 'photo_upload' %>
                <%= hidden_field_tag :retained_image %>
              </div>
            </div>

          </fieldset>
        </div>
      </div>

      <%= hidden_field_tag 'organization[lat]', '', class: 'form-lat' %>
      <%= hidden_field_tag 'organization[lon]', '', class: 'form-lon' %>

      <br/><br/>

      <div class="row">
        <div class="large-4 columns actions">
          <%= button_tag type: 'submit', class: 'button small success' do %>
            <%= image_tag 'save-icon.svg', class: 'ty-icon' %>
            &nbsp;
            Save Organization
          <% end %>

          &nbsp;&nbsp;&nbsp;&nbsp;
          <%= link_to 'Cancel', request.referrer %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="content" id="members">
    <%= render 'members' %>
  </div>

</div>

<br/><br/>

<% if action_name == 'edit' %>
  <%= link_to 'Delete', @organization, method: :delete, class: 'grey', data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/organizations/_members.html.erb
<div class="row">
  <div class="large-8 columns">
    <br/>
    <table class="members">
      <tr>
        <th>Email</th>
        <th>Username</th>
        <th>Status</th>
        <th></th>
      </tr>

      <% if @roles %>
        <% @roles.each do |role| %>
          <tr>

            <td>
              <%= role.user.email %>
            </td>
            <td>
              <%= role.user.username if role.user.username %>
            </td>
            <td>
              <%= role.name %>
            </td>
            <td>
              <%= form_tag organization_role_path(@organization, role), { method: 'PATCH'} do %>

                <%= select_tag 'role[name]', options_for_select([
                                                                        ['', ''],
                                                                        ['Leader', 'leader'],
                                                                        ['Member', 'member'],
                                                                        ['Remove', 'remove']
                                                                ],
                                                                role.name), class: "role_#{role.user.id}"
                %>

                <%= button_tag type: 'submit', class: "button tiny success update_#{role.user.id}" do %>
                  <%= image_tag 'save-icon.svg', class: 'ty-icon' %>
                  &nbsp;
                  Update Status
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      <% else %>
        <p class="grey">No members... yet.</p>
      <% end %>
    </table>
  </div>
</div>

app/views/organizations/edit.html.erb
<div class="small-12 large-12 columns">


  <h1>Editing <%= @organization.name %></h1>

  <br/>

  <%= render 'form' %>


  <br/><br/>
</div>

app/views/organizations/new.html.erb
<h1>New Organization</h1>

<%= render 'form' %>

<br/><br/>

app/views/organizations/show.html.erb
<%= content_for(:title) do %><%= @organization.name %> | <% end %>
<%= content_for(:meta_og) do %>
  <meta property="og:title" content="<%= @organization.name %>" />
  <meta property="og:type" content="website" />
  <meta property="og:description" content="<%= @organization.description %>" />
  <% if @organization.image %>
    <%= tag :meta, property: 'og:image', content: "http://#{request.host}#{@organization.image.url}" %>
  <% end %>
  <meta property="fb:app_id" content="<%= FACEBOOK_CONFIG['app_id'] %>" />
<% end %>

<div class="row">
  <div class="large-6 columns">
    <% if @organization.users.include?(current_user) %>
      <%= link_to new_post_path(organization: @organization.id), class: 'button small' do %>
        <%= image_tag 'plus-icon.svg', class: 'ty-icon' %>
        &nbsp;
        New Post
      <% end %>
    <% end %>
    <br/><br/>

    <ul class="tabs" data-tab>
      <li class="tab-title active"><a href="#posts">Posts</a></li>
      <li class="tab-title"><a href="#members">Members</a></li>
      <li class="tab-title"><a href="#location">Default Location</a></li>
    </ul>

    <div class="tabs-content">
      <div class="content active" id="posts">
        <ul class="posts no-bullet user-list">
          <% @posts.each do |post| %>
            <%= render 'layouts/posts_list', post: post %>
          <% end %>
        </ul>

        <br/><br/>
        <%= will_paginate @posts, renderer: FoundationPagination::Rails %>

        <% if @organization.posts.blank? %>
          <span class="grey">Currently there are no posts.</span>
        <% end %>
      </div>
      <div class="content" id="members">
        <ul class="no-disc member-list user-list">
          <% @organization.users.each do |user| %>
            <li class="shadow-list">
              <% if user.photo %>
                <%= link_to user do %>
                  <%= image_tag user.photo.thumb('75x75#').url %>
                <% end %>
                &nbsp;&nbsp;
              <% end %>
              <%= link_to user.username, user %>

            </li>
          <% end %>

          <% if @organization.users.blank? %>
            <span class="grey">Currently there are no members.</span>
          <% end %>
        </ul>
      </div>
      <div class="content" id="location">
        <ul id="<%= dom_id(@organization) %>" class="location-list no-disc user-list">
          <li class="shadow-list">
            <% if @organization.location %>
              <span id="<%= dom_id(@organization.location) %>">
                <strong><%= @organization.location.name %></strong>
                <br/>
                <span class="location-details">
                  <%= @organization.location.address %>
                  <%= @organization.location.city %>,
                  <%= @organization.location.state %>
                  <%= @organization.location.postcode %>
                </span>
              </span>
            <% else %>
              <p class="grey">No default location set.</p>
            <% end %>
          </li>
        </ul>
      </div>
    </div>

  </div>

  <div class="large-4 columns right card">
    <div class="row">
      <div class="large-12 columns text-center">
        <% if @organization.image %>
          <%= image_tag @organization.image.url, class: 'organization-image',
                        data: { action: 'zoom' },
                        style: 'border: 5px solid ' + @organization.color %>
        <% end %>
      </div>
    </div>

    <div class="row">
      <div class="large-12 columns">
        <%= markdown(@organization.description) %>
        <br/><br/>
      </div>
    </div>

    <div class="row">
      <div class="large-12 columns social">
        <% unless @organization.web_url.blank? %>
          <%= link_to @organization.web_url, target: '_blank' do %>
            <%= image_tag 'globe-icon.svg', class: 'icon' %>
          <% end %>
        <% end %>
        <% unless @organization.facebook_link.blank? %>
          <%= link_to @organization.facebook_link, target: '_blank' do %>
            <% image_tag 'facebook-icon.svg', class: 'image-link' %>
          <% end %>
        <% end %>
        <% unless @organization.twitter_link.blank? %>
          <%= link_to @organization.twitter_link, target: '_blank' do %>
            <% image_tag 'twitter-icon.svg', class: 'image-link' %>
          <% end %>
        <% end %>
        <% unless @organization.google_link.blank? %>
          <%= link_to @organization.google_link, target: '_blank' do %>
            <% image_tag 'google-icon.svg', class: 'image-link' %>
          <% end %>
        <% end %>
        <br/><hr/><br/>
      </div>
    </div>

    <div class="row">
      <div class="columns large-12">
        <% if @leaders.include?(current_user) %>
          <%= link_to edit_organization_path(@organization), class: 'button tiny icon edit-organization', title: 'Edit organization' do %>
            <% image_tag 'edit-icon.svg', class: 'icon' %>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="row">
      <div class="large-12 columns">
        <% if @penders.include?(current_user) %>
          <%= button_tag type: 'submit', class: 'button small secondary disabled' do %>
            <%= image_tag 'group-icon-white.svg', class: 'ty-icon' %>
            &nbsp;
            Join Request Pending...
          <% end %>
        <% elsif current_user && !@organization.users.include?(current_user) %>
          <%= form_tag("/organizations/#{@organization.id}/users", method: 'patch', class: 'join-organization') do |f| %>
            <%= hidden_field_tag 'user_id', current_user.id %>
            <%= button_tag type: 'submit', class: 'button small' do %>
              <%= image_tag 'group-icon-white.svg', class: 'ty-icon' %>
              &nbsp;
              Join <%= @organization.name %>
            <% end %>
          <% end %>
          &nbsp;&nbsp;
        <% end %>

        <% if current_user && !@organization.users.include?(current_user) %>
          <% if current_user.subscriptions.find_by(organization_id: @organization.id) %>
            <%= link_to '#',
                        class: 'button secondary small organization-subscribe',
                        title: 'Unsubscribe from organization',
                        data: { model_id: @organization.id, current_user_id: current_user.id,
                                status: 'subscribed' } do %>

              <%= image_tag 'tack-icon-green.svg', class: 'ty-icon' %>
              Unfollow
            <% end %>
            &nbsp;&nbsp;
          <% else %>
            <%= link_to '#',
                        class: 'button small organization-subscribe',
                        title: 'Subscribe to organization',
                        data: { model_id: @organization.id, current_user_id: current_user.id,
                                status: 'unsubscribed' } do %>
              <%= image_tag 'tack-icon.svg', class: 'ty-icon' %>
              &nbsp;
              Follow
            <% end %>
            &nbsp;&nbsp;
          <% end %>
        <% end %>

      </div>
    </div>
    <div class="large-12 columns map-container">
      <div id="map" class="organization-map"></div>
    </div>

    </div>
</div>


<br/>
<br/>